import Head from 'next/head';

import Section800 from '@/components/home/section/Section800';
import SectionFullWidth from '@/components/home/section/SectionFullWidth';
import { suitExtraBold } from '@/fonts/suitExtraBold';
import { getRandomHex } from '@/utils/color';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <SectionFullWidth>Full width</SectionFullWidth>
        <SectionFullWidth
          cssProps={{
            padding: 0,
            backgroundColor: getRandomHex(),
          }}
        >
          Full width
        </SectionFullWidth>
        <Section800>
          <div
            css={{
              height: 200,
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'center',
              gap: 20,
            }}
          >
            <h1
              css={{
                textAlign: 'center',
              }}
            >
              Hello
            </h1>
            <span>안녕하세요. 반갑습니다. hi hello.</span>
          </div>
        </Section800>
        <Section800
          cssProps={{
            backgroundColor: getRandomHex(),
            height: 200,
          }}
        >
          Second Section
        </Section800>
        <Section800>
          <div className={suitExtraBold.className}>
            어제보다 4℃ 높아요 · Gift 카드 등록하기 · 최대 20% 캐시백 · 61,800P
            적립 · QR 결제
          </div>
        </Section800>
        <Section800>
          <h1>
            어제보다 4℃ 높아요 · Gift 카드 등록하기 · 최대 20% 캐시백 · 61,800P
            적립 · QR 결제
          </h1>
        </Section800>
        <Section800>
          어제보다 4℃ 높아요 · Gift 카드 등록하기 · 최대 20% 캐시백 · 61,800P
          적립 · QR 결제
        </Section800>
      </div>
    </>
  );
}
